name: Regenerate CSS Resources

on:
  workflow_dispatch:
  push:
    branches:
      - patched
  schedule:
    - cron: '47 2 * * *'

jobs:
  deploy:
    runs-on: ubuntu-24.04
    concurrency:
      # Only ever run one at a time to avoid conflicting updates.
      group: ${{ github.workflow }}
      cancel-in-progress: true

    steps:      
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: patched

      - name: Install Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: latest
          extended: true

      - name: Remove Existing exampleSite Resources
        run: rm -rf exampleSite/resources

      - name: Build Example Site
        working-directory: exampleSite
        run: hugo --theme='../..'

      - name: Replace Top-Level Resource Dir
        run: |
          rm -rf resources
          cp -r exampleSite/resources resources

      - name: Commit Back Changes
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0
        with:
          branch: patched
          file_pattern: 'resources/** exampleSite/resources/**'
          commit_message: Regenerate CSS from SCSS
          # push_options: --dry-run
